#!/bin/bash

###################################
#AUTHOR NAME: SAI SUNNY AASHLESH TOGARUCHEETI
#INPUT: GIT CREDENTIALS -- USerName & Token
#PreQ: GITHUB Account with token and organization. Knowledge of shell scripting and 3 commands which consists script to be executed, organization name, and repo name respectively.
#Date&Time: 07/16/2024 1:50A.M
###################################
checker()

# GitHub API URL
API_URL="https://api.github.com"

# GitHub username and personal access token
USERNAME=$username
TOKEN=$token

# User and Repository information
REPO_OWNER=$1
REPO_NAME=$2

# Function to make a GET request to the GitHub API
function url_setup {
    local endpoint="$1"
    local url="${API_URL}/${endpoint}"

    # Send a GET request to the GitHub API with authentication
    curl -s -u "${USERNAME}:${TOKEN}" "$url"
}

# Function to list users with read access to the repository
function list_users_with_read_access {
    local endpoint="repos/${REPO_OWNER}/${REPO_NAME}/collaborators"

    # Fetch the list of collaborators on the repository
    collaborators="$(url_setup "$endpoint" | jq -r '.[] | select(.permissions.pull == true) | .login')"

    # Display the list of collaborators with read access
    if [[ -z "$collaborators" ]]; then
        echo "No users with read access found for ${REPO_OWNER}/${REPO_NAME}."
    else
        echo "Users with read access to ${REPO_OWNER}/${REPO_NAME}:"
        echo "$collaborators"
    fi
}

# Function to check whether the required commands are met.

function checker{
 min=2
 if [ $# -ne $min] ; then 
    echo "OOPS! You might have missed some arguments to get the desired output."
    echo "Please Do Check the Preq's in the script info or look around the code."
}

# Main script

echo "Listing users with read access to ${REPO_OWNER}/${REPO_NAME}..."
list_users_with_read_access
